/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'bschalme' at '1/29/16 8:15 AM' with Gradle 2.10
 *
 * @author bschalme, @date 1/29/16 8:15 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
